<?php

return [
    /*
     * Exports with more rows than this are generated by a queued job and downloaded from the
     * report page when ready; smaller exports stream immediately.
     */
    'sync_export_max_rows' => (int) env('REPORTS_SYNC_EXPORT_MAX_ROWS', 5000),

    'per_page_options' => [25, 50, 100],

    /* Dashboard KPI cache lifetime (seconds); events also invalidate it. */
    'dashboard_cache_ttl' => (int) env('DASHBOARD_CACHE_TTL', 300),

    /* Private disk / directory for queued export files. */
    'export_disk' => 'local',
    'export_directory' => 'report-exports',

    /* Ready export files older than this many days may be pruned. */
    'export_retention_days' => 7,
];
